export const sampleChartData = `
[
  {
     "date":"2022-05-01T00:00:00.000Z",
     "groups":[
        {
           "key":"Compute",
           "amount":171.03
        },
        {
           "key":"Storage",
           "amount":245.77
        },
        {
           "key":"Network",
           "amount":16.27
        }
     ]
  },
  {
     "date":"2022-06-01T00:00:00.000Z",
     "groups":[
        {
           "key":"Compute",
           "amount":235.49
        },
        {
           "key":"Storage",
           "amount":143.56
        },
        {
           "key":"Network",
           "amount":142.33
        }
     ]
  }
]`;